[versions]
# libraries
annotations = "26.1.0"
junit = "4.13.2"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.14.0"
grammarKit = "2023.3.0.3"
qodana = "2025.3.2"
kover = "0.9.8"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
grammarKit = { id = "org.jetbrains.grammarkit", version.ref = "grammarKit" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
